### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 5268: illegal multibyte sequence

### ISSUE THREAD

**Issue by luodeb** [lukassnoek/BidsConverter#16]
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting bidsify
  Downloading https://mirrors.aliyun.com/pypi/packages/d1/0d/1d31da5999ce602d41b4a1ead69426951aff14a14f31f537ed9aa8ddb3fd/bidsify-0.3.7.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Debin\AppData\Local\Temp\pip-install-qmgw28mc\bidsify_84ab1478158f48799a4a4794f5f8ed6d\setup.py", line 13, in <module>
          LONG_DESCRIPTION = f.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 5268: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by lukassnoek** [comment]
Hi, this package is not under development/maintenance anymore, sorry. I'll archive the repo.
