### ISSUE TITLE
Bidsify on Singularity

### ISSUE THREAD

**Issue by steve-svg** [lukassnoek/BidsConverter#9]
Hello,

I am new to Docker and Singularity, so I am a bit confused and unsure. I currently do not have docker installed, but I do have singularity installed. I have created the sif image through singularity pull. After running it, it seems like dcm2niix cannot be found? Would you be able to help me with this?

Thank you so much,
S

**Comment by lukassnoek** [comment]
Hi, at this moment, singularity is not supported, only docker...
And I don't think I have time to implement this, as I'm supposed to finish my PhD this year.
Sorry!
